### ISSUE TITLE
Do not show recipient on log

### ISSUE THREAD

**Issue by GonzaloAlvarez** [markhuge/grunt-mailgun#10]
Upon successfully sending the email, grunt-mailgun shows the recipient for this email. It would be ideal, to avoid spam if we use a public CI environment, like travis, to be able to disable showing it.

https://github.com/markhuge/grunt-mailgun/blob/b39ad157fb8318a11aa88e2b576cc4d586669f06/tasks/mailgun.js#L59

**Comment by markhuge** [comment]
@GonzaloAlvarez that sounds reasonable. Try this branch out and let me know if it accomplishes what you're looking for: https://github.com/markhuge/grunt-mailgun/tree/feature/10

You can include this branch as a dependency in your package.json like this:

`"grunt-mailgun": "git://github.com/markhuge/grunt-mailgun.git#feature/10"`

Once you confirm I can merge/bump and push a new release to npm.

**Comment by GonzaloAlvarez** [comment]
Didn't work. Seems that you are missing a bit:

https://github.com/markhuge/grunt-mailgun/blob/feature/10/tasks/mailgun.js#L46

there you should also copy the value for the hideRecipient property from opts to options.

As a friendly suggestion, I would say it would be cleaner to pass the opts object to the send function instead of creating a new one.

**Comment by markhuge** [comment]
Aaaaaand that's why I shouldn't make edits from my phone. I'll fix when I'm back home.

**Comment by markhuge** [comment]
@GonzaloAlvarez this whole codebase was super old so I did some refactoring and cleanup. Give it a shot now.

**Comment by GonzaloAlvarez** [comment]
Great @markhuge !! Now it is working perfectly!!

Thanks a ton for that awesome work!

**Comment by markhuge** [comment]
@GonzaloAlvarez ty and happy to help! I'm waiting on some feedback from a few companies who are using this and then I'm pushing out the next release to npm.
