### ISSUE TITLE
Error: 403

### ISSUE THREAD

**Issue by reellz** [markhuge/grunt-mailgun#11]
Hi,

I always get an 403 error code if I run the mailgun task. By using the curl test command it works fine. So the credentials should be fine. Attached is an screenshot where you can see the output.

Do you have an idea what the problem is?

Thanks and best,
Christian

![bildschirmfoto 2015-10-07 um 11 22 24](https://cloud.githubusercontent.com/assets/325100/10333719/0650c69e-6ce6-11e5-98dc-84a1fbcece7d.png)

**Comment by markhuge** [comment]
@reellz grunt-email-workflow is using  `0.2.1` as a dependency. Can you try replacing that with grunt-mailgun `1.0.0`?

**Comment by markhuge** [comment]
@reellz did you try 1.0.0? Did this resolve the issue?

**Comment by markhuge** [comment]
Closing this out due to inactivity/inability to reproduce. If this is still a problem, let me know and I'm happy to help!

**Comment by reellz** [comment]
@markhuge Sorry for the late response. Updating to the latest version fixed this issue. Thanks!
