### ISSUE TITLE
Mailgun stuck sending..

### ISSUE THREAD

**Issue by luis-sanchez-jd** [markhuge/grunt-mailgun#13]
Hi 
version mailgun 0.2.1, 

I m getting the error 403(local with webstorm and our sever), Searching here I found it can be fix with the update, so I stared the update (1.0.1). Now my local and server stuck on sending email

this issue started happening yesterday

let me now if you need more information of setup or other detail 

![untitled](https://cloud.githubusercontent.com/assets/16802961/20855871/f76d7f7a-b8c8-11e6-9754-6e32435619ec.png)

**Comment by markhuge** [comment]
I believe this issue had to do with mailgun api changes. should be resolved in 2.0.0
