### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by toby1kenobi** [markhuge/grunt-mailgun#14]
I think it's possible this is no longer working. It was very recently, but on my Windows 10 laptop no mail is sent any more, even though it reports success:

    Running "mailgun:mailer" (mailgun) task
    Sent mailgun msg to mytestingemail@litmustest.com

**Comment by markhuge** [comment]
mailgun changed their api. updating upstream lib with their new sdk. see : https://github.com/markhuge/node-mailgun-send/tree/mailgun-official-sdk

**Comment by markhuge** [comment]
This should be resolved in 2.0.0
