### ISSUE TITLE
Is it possible to define a domain?

### ISSUE THREAD

**Issue by leemunroe** [markhuge/grunt-mailgun#4]
If I have multiple Mailgun domains, how do I define what domain to send the email(s) from?

**Comment by markhuge** [comment]
@leemunroe Apologies, day job and holiday/family stuff took priority over open source stuff for a few weeks. Under the hood I'm relying on the mailgun npm module to negotiate the Mailgun API.

It looks like there's a PR to add the support you want [here](https://github.com/shz/node-mailgun/pull/7/files), but it's super old and looks like it's been ignored by the maintainer.

So there's a few options here:

1. We don't add that functionality (boo)
2. You can confirm the PR in question does what you're asking (and I'm not just misreading), and then we appeal to the maintainer to give it some attention.
3. We find a mailgun API module that has those features and use that instead.
4. You/me/someone forks the node-mailgun repo and adds all the modern API stuff.

Thoughts?

**Comment by markhuge** [comment]
Also looping in @davidturner since he's maintaining  gulp-mailgun (which I personally prefer over grunt)  and is in the same boat.

**Comment by leemunroe** [comment]
Thanks for the follow up. No problem, was curious if there was a way to do it already that I was overlooking. Not a blocker for me. What you've implemented already works great for my use case :-)
